apiVersion: v1
kind: Pod
metadata:
    name: jenkins-agent

spec:
  containers:
  - name: inbound-agent
    image: jenkins/inbound-agent
    command: ['sh', '-c']
    args:
    - 'echo "Hello, World!" && sleep 99d'
    tty: true
    ports:
    - containerPort: 80