pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '30'))
        disableConcurrentBuilds()
    }
 
    stages {
        stage("Docker build") {

            steps {
                script {
                    dockerfile.build_and_push()
                }
            }
        }
    }
}